### ISSUE TITLE
Facing issues while file is getting large.

### ISSUE THREAD

**Issue by anigos** [MrPowers/spark-stringmetric#11]
Hey I am getting issues while computing the cosine_distance while file size getting larger than 1m records. It runs fine with 10k records.

---------------------------------
.withColumn(
      "cd_SrcTrg",
      cosine_distance(col("Src"), col("Trg")) 
    )
-------------------------------------

20/08/09 22:29:38 INFO DAGScheduler: ShuffleMapStage 3 (csv at CosineDistance.scala:133) failed in 6.574 s due to Job aborted due to stage failure: Task 9 in stage 3.0 failed 1 times, most recent failure: Lost task 9.0 in stage 3.0 (TID 34, localhost, executor driver): org.apache.spark.SparkException: Failed to execute user defined function(anonfun$1: (string, string) => double)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.agg_doAggregateWithKeys_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid text
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:158)
	at org.apache.commons.text.similarity.RegexTokenizer.tokenize(RegexTokenizer.java:43)
	at org.apache.commons.text.similarity.RegexTokenizer.tokenize(RegexTokenizer.java:34)
	at org.apache.commons.text.similarity.CosineDistance.apply(CosineDistance.java:49)
	at com.github.mrpowers.spark.stringmetric.SimilarityFunctions$.cosineDistanceFun(SimilarityFunctions.scala:17)
	at com.github.mrpowers.spark.stringmetric.SimilarityFunctions$$anonfun$1.apply(SimilarityFunctions.scala:11)
	at com.github.mrpowers.spark.stringmetric.SimilarityFunctions$$anonfun$1.apply(SimilarityFunctions.scala:11)
	... 15 more

**Comment by anigos** [comment]
I believe it is not able to handle some value in the src and trg column which are not valid text.

**Comment by MrPowers** [comment]
@anigos - thanks for opening this issue.  Looks like you got past your blocking issue.  If anything else comes up, just let me know.  Thanks for using this library!
